// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleShop.Repositories;

namespace SimpleShop.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20200906182130_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimpleShop.Models.OrderItem", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SimpleShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfItemsInStock")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Product1",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Product2",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Product3",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Product4",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Product5",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Product6",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Product7",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Product8",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Product9",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "Product10",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Product11",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Product12",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            Id = 13,
                            Name = "Product13",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 2
                        },
                        new
                        {
                            Id = 14,
                            Name = "Product14",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 2
                        },
                        new
                        {
                            Id = 15,
                            Name = "Product15",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 2
                        },
                        new
                        {
                            Id = 16,
                            Name = "Product16",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 2
                        },
                        new
                        {
                            Id = 17,
                            Name = "Product17",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 3
                        },
                        new
                        {
                            Id = 18,
                            Name = "Product18",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 3
                        },
                        new
                        {
                            Id = 19,
                            Name = "Product19",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 3
                        },
                        new
                        {
                            Id = 20,
                            Name = "Product20",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 4
                        },
                        new
                        {
                            Id = 21,
                            Name = "Product21",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 4
                        },
                        new
                        {
                            Id = 22,
                            Name = "Product22",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 4
                        },
                        new
                        {
                            Id = 23,
                            Name = "Product23",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 5
                        },
                        new
                        {
                            Id = 24,
                            Name = "Product24",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 5
                        },
                        new
                        {
                            Id = 25,
                            Name = "Product25",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 5
                        },
                        new
                        {
                            Id = 26,
                            Name = "Product26",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 5
                        },
                        new
                        {
                            Id = 27,
                            Name = "Product27",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 6
                        },
                        new
                        {
                            Id = 28,
                            Name = "Product28",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 6
                        },
                        new
                        {
                            Id = 29,
                            Name = "Product29",
                            NumberOfItemsInStock = 100,
                            Price = 100.0,
                            ProductCategoryId = 6
                        });
                });

            modelBuilder.Entity("SimpleShop.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Category1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Category2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Category3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Category4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Category5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Category6"
                        });
                });

            modelBuilder.Entity("SimpleShop.Models.OrderItem", b =>
                {
                    b.HasOne("SimpleShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimpleShop.Models.Product", b =>
                {
                    b.HasOne("SimpleShop.Models.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
